[workspace]
members = [
  "amqp-type",
  "amqp-transport",
  "amqp-messaging",
  "amqp-transaction",
  "amqp-security",
]
resolver = "2"

[workspace.dependencies]
thiserror = "1.0.47"
tokio = {version = "1", features=["full"]}
uuid = {version = "1.4.1", features = ["v4"]}
tokio-stream = "0.1.16"