[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amqp-lib = {path = "../amqp-lib"}
anyhow = "1.0.75"
tokio = {version = "1", features=["full"]}
tracing = "0.1.37"
